/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 playwright/.cache/models/chair_styloo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chair_styloo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chair.geometry} material={materials.bois} position={[-8.053, 0.862, -9.238]} rotation={[0, 0, Math.PI]} scale={1.144} />
    </group>
  )
}

useGLTF.preload('/chair_styloo.glb')
