/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/misc.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/misc.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Guitar.geometry} material={materials.Guitar_Material} position={[12.293, -0.635, -4.06]} />
      <mesh geometry={nodes.Wrench.geometry} material={materials.Wrench_Material} position={[-12.219, 0, 0.852]} />
      <mesh geometry={nodes.Camera.geometry} material={materials.Camera_Material} position={[6.411, 0.383, 2.284]} />
      <mesh geometry={nodes.Case.geometry} material={materials.Case_Material} position={[8.551, 0.172, -0.306]} />
      <mesh geometry={nodes.Hotdog.geometry} material={materials.Hotdog_Material} position={[15.932, -0.193, -2.018]} />
      <mesh geometry={nodes.Money.geometry} material={materials.Money_Material} position={[4.321, -0.175, -0.161]} />
      <mesh geometry={nodes.Money_Case.geometry} material={materials.Money_Case_Material} position={[6.194, -0.01, 0.002]} />
      <mesh geometry={nodes.Plier.geometry} material={materials.Plier_Material} position={[-0.034, 0, 0]} />
      <mesh geometry={nodes.Polaroid.geometry} material={materials.Polaroid_Material} position={[14.681, -0.032, -2.09]} />
      <mesh geometry={nodes.Radio.geometry} material={materials.Radio_Material} position={[13.512, 0.069, -2.089]} />
      <mesh geometry={nodes.Saw.geometry} material={materials.Saw_Material} position={[0.846, 1.094, 2.004]} />
      <mesh geometry={nodes.Screwdriver.geometry} material={materials.Screwdriver_Material} position={[-13.411, 0.008, -4.041]} />
      <mesh geometry={nodes.Toolbox.geometry} material={materials.Toolbox_Material} position={[9.721, 0.172, -0.107]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Torch_1} position={[-12.641, 0.008, -4.977]} />
      <mesh geometry={nodes.Torch_2.geometry} material={materials.Torch_2_Material} position={[-12.075, 0.008, -4.977]} />
      <mesh geometry={nodes.Torch_3.geometry} material={materials.Torch_3_Material} position={[-11.444, 0.008, -4.977]} />
      <mesh geometry={nodes.Torch_4.geometry} material={materials.Torch_4_Material} position={[-10.344, 0.114, -4.767]} />
      <mesh geometry={nodes.Key_1.geometry} material={materials.Key_1_Material} position={[-11.026, 0.071, 0.137]} />
      <mesh geometry={nodes.Key_2.geometry} material={materials.Key_2_Material} position={[-9.885, 0.071, -0.377]} />
      <mesh geometry={nodes.Key_3.geometry} material={materials.Key_3_Material} position={[-8.863, 0.071, 0.147]} />
      <mesh geometry={nodes.Lock_1.geometry} material={materials.Lock_1_Material} position={[16.236, 0.303, -0.626]} />
      <mesh geometry={nodes.Lock_2.geometry} material={materials.Lock_2_Material} position={[9.345, 0.328, -2.347]} />
      <mesh geometry={nodes.Phone_1.geometry} material={materials.Phone_1_Material} position={[13.427, 0.3, -0.214]} />
      <mesh geometry={nodes.Phone_2.geometry} material={materials.Phone_2_Material} position={[14.228, 0.3, -0.214]} />
      <mesh geometry={nodes.Pickaxe.geometry} material={materials.Pickaxe_Material} position={[-1.364, 0.138, 1.763]} />
      <mesh geometry={nodes.Pizza.geometry} material={materials.Pizza_Material} position={[-7.174, -0.004, 1.49]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.PizzaBox} position={[-7.178, -0.001, -0.386]} />
      <mesh geometry={nodes.Pizza_Slice.geometry} material={materials.Pizza_Slice_Material} position={[15.28, 0.137, -0.71]} />
      <mesh geometry={nodes.Poster_Missing.geometry} material={materials.Poster_Missing_Material} position={[2.691, 0.137, 0.309]} />
      <mesh geometry={nodes.Shovel_1.geometry} material={materials.Shovel_1_Material} position={[-5.493, 0.16, 1.458]} />
      <mesh geometry={nodes.Shovel_2.geometry} material={materials.Shovel_2_Material} position={[-3.832, 0.16, 1.516]} />
      <mesh geometry={nodes.Toilet_Paper.geometry} material={materials.Toilet_Paper_Material} position={[11.759, 0.137, -0.325]} />
      <mesh geometry={nodes.Battery.geometry} material={materials.Battery_Material} position={[-12.982, 0, 0.301]} />
      <mesh geometry={nodes.Bottle_1.geometry} material={materials.Bottle_1_Material} position={[10.053, 0.137, -2.347]} />
      <mesh geometry={nodes.Burger.geometry} material={materials.Burger_Material} position={[11.648, 0.219, -2.35]} />
      <mesh geometry={nodes.Cigarette_Pack.geometry} material={materials.Cigarette_Pack_Material} position={[10.553, 0.584, -0.341]} />
      <mesh geometry={nodes.Drill.geometry} material={materials.Drill_Material} position={[12.484, 0.253, -2.347]} />
      <mesh geometry={nodes.Zippo.geometry} material={materials.Zippo} position={[-9.032, 1.038, -4.842]} />
      <mesh geometry={nodes.Radio001.geometry} material={materials['Radio_Material.001']} position={[-8.263, 1.1, -4.812]} />
      <mesh geometry={nodes.PS1.geometry} material={materials.PS1} position={[-0.233, 0.877, -4.969]} />
      <mesh geometry={nodes.Pot.geometry} material={materials.Pot} position={[-6.036, 1.103, -5.04]} />
      <mesh geometry={nodes.Pen.geometry} material={materials.Pen} position={[7.722, 1.22, -5.047]} />
      <mesh geometry={nodes.Pan.geometry} material={materials.Pan} position={[-4.78, 0.863, -5.04]} />
      <mesh geometry={nodes.Nail.geometry} material={materials.Nail} position={[-2.417, 0.961, -5.064]} />
      <mesh geometry={nodes.Meds.geometry} material={materials.Meds} position={[-2.925, 1.091, -5.047]} />
      <mesh geometry={nodes.Lasagna_Tray.geometry} material={materials.Lasagna_Tray} position={[6.819, 0.872, -5.047]} />
      <mesh geometry={nodes.Lasagna.geometry} material={materials.Lasagna} position={[6.792, 0.779, -4.327]} />
      <mesh geometry={nodes.Harddrive.geometry} material={materials.Harddrive} position={[-1.349, 0.659, -5.047]} />
      <mesh geometry={nodes.Gas_V3.geometry} material={materials.Gas_V3} position={[1.158, 1.25, -5.144]} />
      <mesh geometry={nodes.Gas_V2.geometry} material={materials.Gas_V2} position={[2.449, 1.597, -5.047]} />
      <mesh geometry={nodes.Gas_V1.geometry} material={materials.Gas_V1} position={[3.579, 2.153, -5.043]} />
      <mesh geometry={nodes.Gas_Stove.geometry} material={materials.Gas_Stove} position={[-7.09, 1.28, -4.837]} />
      <mesh geometry={nodes.Donut.geometry} material={materials.Donut} position={[5.634, 0.681, -5.047]} />
      <mesh geometry={nodes.Crowbar.geometry} material={materials.Crowbar} position={[-1.864, 1.914, -4.91]} />
      <mesh geometry={nodes.CD.geometry} material={materials.CD} position={[4.64, 0.554, -5.047]} />
      <mesh geometry={nodes.Brick.geometry} material={materials.Brick} position={[-3.631, 0.811, -5.047]} />
      <mesh geometry={nodes.Blunt.geometry} material={materials.Blunt} position={[7.675, 0.811, -4.681]} />
    </group>
  )
}

useGLTF.preload('/misc.glb')
