/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 playwright/.cache/models/table_styloo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/table_styloo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.table.geometry} material={materials.bois} position={[-8.638, 1.266, -5.539]} scale={0.778} />
    </group>
  )
}

useGLTF.preload('/table_styloo.glb')
