// Jest mock for AudioEngine — all audio methods are no-ops in tests.
const audioEngine = {
  initialize: jest.fn().mockResolvedValue(undefined),
  initialized: true,
  playSound: jest.fn(),
  playChop: jest.fn(),
  setSizzleLevel: jest.fn(),
  setGrinderSpeed: jest.fn(),
  setAmbientDrone: jest.fn(),
  startAmbient: jest.fn(),
  stopAmbient: jest.fn(),
  setVolume: jest.fn(),
  setMuted: jest.fn(),
  isMuted: jest.fn().mockReturnValue(false),
  dispose: jest.fn(),
  // Legacy method names (from old main branch audio engine)
  initTone: jest.fn().mockResolvedValue(undefined),
  startGrinder: jest.fn(),
  stopGrinder: jest.fn(),
  playStuffingSquelch: jest.fn(),
  playCountdownBeep: jest.fn(),
  startBlowWhoosh: jest.fn(),
  stopBlowWhoosh: jest.fn(),
  playSlam: jest.fn(),
  playSizzle: jest.fn(),
  playCorrectPick: jest.fn(),
  playWrongPick: jest.fn(),
  updatePressure: jest.fn(),
  stopPressure: jest.fn(),
  playBurst: jest.fn(),
  playTitleJingle: jest.fn(),
  playRatingSong: jest.fn(),
  startAmbientDrone: jest.fn(),
  stopAmbientDrone: jest.fn(),
  stopEngine: jest.fn(),
  playSample: jest.fn(),
  startSampleLoop: jest.fn(),
  stopSampleLoop: jest.fn(),
  playGrab: jest.fn(),
  playDrop: jest.fn(),
  playPour: jest.fn(),
  playMix: jest.fn(),
  startCookingSizzle: jest.fn(),
  stopCookingSizzle: jest.fn(),
  playSizzleHit: jest.fn(),
  playBoiling: jest.fn(),
};

module.exports = {audioEngine};
